### ISSUE TITLE
Support iOS

### ISSUE THREAD

**Issue by robert-virkus** [Enough-Software/enough_html_editor#22]
Currently the editor does not work at all on iOS.

In principle, contenteditable should work fine:

- https://webkit.org/blog/7358/enhanced-editing-with-input-events/
- https://stackoverflow.com/questions/4251227/contenteditable-div-not-actually-editable-in-webkit

**Comment by GuilhermeDemoliner** [comment]
Have any workarround to the current version 0.0.4?
